In [2]:
import numpy as np

In [4]:
t = np.array(
    [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]
)

print(t)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [5]:
print ('Rank of t: ', t.ndim)
print ('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (10,)


In [ ]:
print ('t[0] t[1] t[-1] =', t[0], t[1], t[-1]) #Element

print ("t[2:5], t[4:-1] =", t[2:5], t[4:-1]) #Slicing

print ("t[:2] t[3:] =", t[:2], t[3:]) #Slicing

t[0] t[1] t[-1] = 0.0 1.0 9.0
t[2:5], t[4:-1] = [2. 3. 4.] [4. 5. 6. 7. 8.]
t[:2] t[3:] = [0. 1.] [3. 4. 5. 6. 7. 8. 9.]


In [4]:
t= np.array(
    [
        [
            [1,2],[2,3]
        ],
        [
            [3,4],[4,5]
        ]
    ]
)
print(t)

[[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]]


In [6]:
print("Rank of t: ", t.ndim)
print("Shape of t : ", t.shape)


Rank of t:  3
Shape of t :  (2, 2, 2)


In [9]:
import torch

t_1 = torch.FloatTensor(
    [0., 1., 2., 3., 4., 5., 6., 7.,]
)
print(t_1)

tensor([0., 1., 2., 3., 4., 5., 6., 7.])


In [ ]:
print(t_1.dim())
print(t_1.shape)
print(t_1.size())
print(t_1[0], t_1[1], t_1[-1])
print(t_1[2:5], t_1[4:-1])
print(t_1[:2], t_1[3:])


1
